PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users(
    id integer NOT NULL PRIMARY KEY autoincrement,
    nom varchar(255) NOT NULL,
    prenom varchar(255),
    email varchar(200) not null,
    telephone varchar(30),
    adresse varchar(200),
    password varchar(100),
    role varchar(20)
);
INSERT INTO users VALUES(1,'Ramilison','Abraham','abrahamramilison@gmail.com','','','$2b$10$o50eF5eienY790vezvRpku6NSz9lCQ6ntUkOYNFYlGnpaqWoJSKDi','Client');
INSERT INTO users VALUES(2,'ram','abrr','abraham@gmail.com','0343233380','Andoharanofotsy','$2b$10$Yebxy8FePwiE.fysQcu8MOnkIOkatJP96BCNuTnXmrBBDvVKYNW5q','Atelier');
CREATE TABLE villes(
    id integer NOT NULL PRIMARY KEY autoincrement,
    nom text NOT NULL,
    longitude real NOT NULL,
    latitude real NOT NULL
);
INSERT INTO villes VALUES(1,'global',0.0,0.0);
INSERT INTO villes VALUES(2,'Antananarivo',47.517299999999998761,-18.891504000000001184);
INSERT INTO villes VALUES(3,'Mahajanga',46.343246000000000604,-15.695517000000000606);
INSERT INTO villes VALUES(4,'Toamasina',49.394193000000001349,-18.148496000000001515);
INSERT INTO villes VALUES(5,'Toliara',43.690067999999996572,-23.356096999999998331);
INSERT INTO villes VALUES(6,'Antsiranana',49.292644000000002792,-12.311559000000000807);
INSERT INTO villes VALUES(7,'Fianarantsoa',47.087316000000001281,-21.452559000000000822);
CREATE TABLE IF NOT EXISTS "articles"(
    id integer NOT NULL PRIMARY KEY autoincrement,
    titre varchar(255) NOT NULL,
    descr varchar(255),
    contenu text, -- contenu de l'article (HTML)
    date_pub text,
    date_modif text, video text, longitude decimal, latitude decimal
);
INSERT INTO articles VALUES(11,'Vato Beach','Espace',replace('<h1>Hello, World!</h1> <ol> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ol> <ul> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ul> <p>Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</p> <a href=''facebook.com''>Cliquez ici</a> <div> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. <hr> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. </div> <h2>Bye, World!</h2>\n','\n',char(10)),'2023-08-06 19:41:14','2023-08-06 19:41:14','',47.530146100000003174,-18.985973099999998936);
INSERT INTO articles VALUES(12,'Park de Timbazaza','Park',replace('<h1>Hello, World!</h1> <ol> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ol> <ul> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ul> <p>Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</p> <a href=''facebook.com''>Cliquez ici</a> <div> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. <hr> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. </div> <h2>Bye, World!</h2>\n','\n',char(10)),'2023-08-06 19:41:14','2023-08-06 19:41:14','',47.530146100000003174,-18.985973099999998936);
INSERT INTO articles VALUES(13,'Rova de Manjakamiadana','Patrimoine historique',replace('<h1>Hello, World!</h1> <ol> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ol> <ul> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ul> <p>Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</p> <a href=''facebook.com''>Cliquez ici</a> <div> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. <hr> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. </div> <h2>Bye, World!</h2>\n','\n',char(10)),'2023-08-06 19:41:14','2023-08-06 19:41:14','PumQIUVuqjc',47.530146100000003174,-18.985973099999998936);
INSERT INTO articles VALUES(14,'Tsingy de Bemaraha','Park',replace('<h1>Hello, World!</h1> <ol> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ol> <ul> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ul> <p>Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</p> <a href=''facebook.com''>Cliquez ici</a> <div> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. <hr> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. </div> <h2>Bye, World!</h2>\n','\n',char(10)),'2023-08-06 19:41:14','2023-08-06 19:41:14','4ZkxIAj2zc0',47.530146100000003174,-18.985973099999998936);
INSERT INTO articles VALUES(15,'KFC Gasy','Fast Food',replace('<h1>Hello, World!</h1> <ol> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ol> <ul> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ul> <p>Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</p> <a href=''facebook.com''>Cliquez ici</a> <div> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. <hr> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. </div> <h2>Bye, World!</h2>\n','\n',char(10)),'2023-08-06 19:41:14','2023-08-06 19:41:14','',47.530146100000003174,-18.985973099999998936);
INSERT INTO articles VALUES(16,'Celtel Hotel','Hotel et relaxation',replace('<h1>Hello, World!</h1> <ol> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ol> <ul> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ul> <p>Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</p> <a href=''facebook.com''>Cliquez ici</a> <div> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. <hr> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. </div> <h2>Bye, World!</h2>\n','\n',char(10)),'2023-08-06 19:41:14','2023-08-06 19:41:14','',47.530146100000003174,-18.985973099999998936);
INSERT INTO articles VALUES(17,'Rakiki au Palais des sports','Evenement culturel',replace('<h1>Hello, World!</h1> <ol> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ol> <ul> <li>test</li> <li>ok</li> <li>asdf</li> <li>wawa</li> </ul> <p>Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.</p> <a href=''facebook.com''>Cliquez ici</a> <div> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. <hr> Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat. </div> <h2>Bye, World!</h2>\n','\n',char(10)),'2023-08-06 19:41:14','2023-08-06 19:41:14','',47.530146100000003174,-18.985973099999998936);
INSERT INTO articles VALUES(18,'test','test','<h1>test</h1>','2023-08-06 19:41:14','2023-08-06 19:41:14','x0CLkcTrKpc',47.530146100000003174,-18.985973099999998936);
CREATE TABLE IF NOT EXISTS "images"(
            id integer NOT NULL PRIMARY KEY autoincrement,
            date_modif text,
            article int,
            bytes blob,
            FOREIGN KEY (article) REFERENCES articles(id)
            );
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('users',2);
INSERT INTO sqlite_sequence VALUES('villes',7);
INSERT INTO sqlite_sequence VALUES('articles',18);
COMMIT;
