# @baseUrl = https://m1p10mean.onrender.com/
# @baseUrl = https://tourisme-mada-m1p10android.onrender.com/api

@baseUrl = https://cc5e-41-77-20-8.ngrok-free.app/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVm9uankiLCJ1c2VySWQiOjIsImlhdCI6MTY5MTIzMjA5MywiZXhwIjoxNjkxMjM1NjkzfQ.FpF7CZO8DLC4Lwxm2qVr-9v_05pjVjgEuq8x0gWX2WM



###
POST {{baseUrl}}/auth/inscription HTTP/1.1
Content-Type: application/json

{
    "nom":"Abrr",
    "prenom":"Ram",
    "password":"123456",
    "email":"abraham@gmail.com",
    "telephone":"0342456542",
    "adresse":"Antanimena",
    "role":"Atelier"
}

###
POST {{baseUrl}}/auth/inscription HTTP/1.1
Content-Type: application/json

{
    "nom":"Vonjy",
    "prenom":"Ranjelison",
    "password":"123456",
    "email":"vonjy@gmail.com",
    "telephone":"0342456542",
    "adresse":"Mahamasina",
    "role":"Atelier"
}

###

POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"vonjy@gmail.com",
    "password":"123456"
}


###

GET {{baseUrl}}/auth/allUser HTTP/1.1
Authorization: Bearer {{token}}
