# @baseUrl = https://m1p10mean.onrender.com/

@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWJyciIsInVzZXJJZCI6MiwiaWF0IjoxNjkwNzk1NTU2LCJleHAiOjE2OTA3OTkxNTZ9.LX6ddCySE4ha1_RfFWxmHiSzVBiV3p-mGpNKyRXjCZw


###
POST {{baseUrl}}/auth/inscription HTTP/1.1
Content-Type: application/json

{
    "nom":"Abrr",
    "prenom":"Ram",
    "password":"123456",
    "email":"abraham@gmail.com",
    "telephone":"0342456542",
    "adresse":"Antanimena",
    "role":"Client"
}

###

POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"tahina@gmail.com",
    "password":"123456"
}


###

GET {{baseUrl}}/auth/allUser HTTP/1.1
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/article HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/article HTTP/1.1
Content-Type: application/json

{
    "titre":"titre",
    "descr":"description",
    "contenu":"contenu",
}
